# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: en-US
tone_instructions: "Maintain a helpful and encouraging tone. Focus on providing constructive feedback."
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai title"
  auto_title_instructions: "Generate a concise and descriptive PR title that reflects the changes."
  review_status: true
  commit_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  poem: false
  labeling_instructions:
    - label: "bug"
      instructions: "This PR appears to be fixing a bug."
    - label: "feature"
      instructions: "This PR introduces a new feature."
    - label: "enhancement"
      instructions: "This PR improves an existing feature."
    - label: "documentation"
      instructions: "This PR contains changes to documentation."
    - label: "refactor"
      instructions: "This PR refactors existing code without changing its external behavior."
  path_filters:
    - "**/*.js"
    - "**/*.md"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/*.lock"
    - "!.github/**"
  path_instructions:
    - path: "**/*.js"
      instructions: "Please review this JavaScript code for adherence to our coding standards, paying close attention to potential race conditions and error handling. Ensure all new functions are documented with JSDoc comments."
    - path: "database.js"
      instructions: "Scrutinize any changes to the database schema for potential migration issues and performance implications. All schema changes must be backward compatible."
    - path: "**/*.md"
      instructions: "Check for clarity, grammar, and formatting. Ensure all links are valid."
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
      - "development"
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  tools:
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    shellcheck:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      disabled_rules:
        - "UPPERCASE_SENTENCE_START"
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/docs/coding-standards.md"
  learnings:
    scope: "auto"
  issues:
    scope: "auto"